# Generated by Django 6.1.1 on 2026-10-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('issue_type', models.CharField(max_length=255)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('ticket_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
